repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1          # pin the exact version you like
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
